package com.techno.player2.data_source;

import com.techno.player2.models.Movie;

import java.util.ArrayList;
import java.util.List;

public class DataSourceTVChannelsAll {
    
    public static List<Movie> getChannels() {
        List<Movie> listChannels = new ArrayList<>();
        listChannels.add(new Movie("Event TV","https://i.ibb.co/4P223m5/event.jpg"));
        listChannels.add(new Movie("Тасма Кино","https://i.ibb.co/PgfjNcz/image.jpg"));
        listChannels.add(new Movie("КТРК","https://i.ibb.co/DkbJ43S/image.jpg"));
        listChannels.add(new Movie("НТС", "https://i.ibb.co/tqc4mxJ/image.jpg"));
        listChannels.add(new Movie("Любимый HD","https://i.ibb.co/6bY2Xnb/image.jpg"));
        listChannels.add(new Movie("New TV","https://i.ibb.co/gVt9YBV/image.jpg"));
        listChannels.add(new Movie("7 Канал","https://i.ibb.co/D4gZyg7/7.jpg"));
        listChannels.add(new Movie("ТНТ Кыргызстан","https://i.ibb.co/k8KLJyX/image.jpg"));
        listChannels.add(new Movie("НТВ KG","https://i.ibb.co/3WKpKzY/kg.jpg"));
        listChannels.add(new Movie("Пирамида HD","https://i.ibb.co/y637ZWv/image.jpg"));
        listChannels.add(new Movie("ОШ ТВ","https://i.ibb.co/sVjBs07/image.jpg"));
        listChannels.add(new Movie("Ош Пирим","https://i.ibb.co/tHzb64T/image.jpg"));
        listChannels.add(new Movie("Семейный","https://i.ibb.co/XzLRs5w/image.jpg"));
        listChannels.add(new Movie("РЕН ТВ","https://i.ibb.co/pwGPwmZ/image.jpg"));
        listChannels.add(new Movie("Первый Канал", "https://i.ibb.co/YPThff6/image.jpg"));
        listChannels.add(new Movie("Первый Канал HD","https://i.ibb.co/vYqTdhG/hd.jpg"));
        listChannels.add(new Movie("Россия 1 HD","https://i.ibb.co/HDMGKp4/1.jpg"));
        listChannels.add(new Movie("Россия РТР","https://i.ibb.co/wKJPSff/image.jpg"));
        listChannels.add(new Movie("Жаша! HD","https://i.ibb.co/XVjg88x/image.jpg"));
        listChannels.add(new Movie("Super TV HD","https://i.ibb.co/9HctSLk/super-tv.jpg"));
        listChannels.add(new Movie("Азия ТВ","https://i.ibb.co/tDQ1VdC/image.jpg"));
        listChannels.add(new Movie("Ынтымак","https://i.ibb.co/YbqVmJY/image.jpg"));
        listChannels.add(new Movie("ЭлТР Кыргызстан","https://i.ibb.co/BfFxWP7/1.jpg"));
        listChannels.add(new Movie("5 Канал","https://i.ibb.co/3MNdqrj/5.jpg"));
        listChannels.add(new Movie("Manas HD","https://i.ibb.co/ykDg0Gn/image.jpg"));
        listChannels.add(new Movie("9 Канал","https://i.ibb.co/R0KJH36/9.jpg"));
        listChannels.add(new Movie("МИР","https://i.ibb.co/X37H4pR/image.jpg"));
        listChannels.add(new Movie("СТС","https://i.ibb.co/h8ryJ6W/image.jpg"));
        listChannels.add(new Movie("Fashion TV","https://i.ibb.co/z6v76By/image.jpg"));
        listChannels.add(new Movie("Психология","https://i.ibb.co/r2zBxyT/image.jpg"));
        listChannels.add(new Movie("Живи!","https://i.ibb.co/hLVJJZM/image.jpg"));
        listChannels.add(new Movie("Сарафан","https://i.ibb.co/WHPM3f4/image.jpg"));
        listChannels.add(new Movie("Ю-ТВ","https://i.ibb.co/hcHWQsZ/image.jpg"));
        listChannels.add(new Movie("Здоровое ТВ","https://i.ibb.co/N1STcyW/image.jpg"));
        listChannels.add(new Movie("Время","https://i.ibb.co/WFndqQZ/image.jpg"));
        listChannels.add(new Movie("Усадьба","https://i.ibb.co/kqt7ygt/image.jpg"));
        listChannels.add(new Movie("ТВЦ","https://i.ibb.co/mJvnZPQ/1.jpg"));
        listChannels.add(new Movie("312 ТВ","https://i.ibb.co/WtSgm67/312.jpg"));
        listChannels.add(new Movie("312 Кино HD","https://i.ibb.co/vX9vgyt/312.jpg"));
        listChannels.add(new Movie("Телекафе","https://i.ibb.co/kGFFw1m/image.jpg"));
        listChannels.add(new Movie("Спас ТВ","https://i.ibb.co/3yvGD04/image.jpg"));
        listChannels.add(new Movie("Союз","https://i.ibb.co/sKvbRvV/1.jpg"));
        listChannels.add(new Movie("Беларусь 24","https://i.ibb.co/xH4ZLQk/24.jpg"));
        listChannels.add(new Movie("БелРос","https://i.ibb.co/Qb7mxTB/image.jpg"));
        listChannels.add(new Movie("RTG TV","https://i.ibb.co/nzk2Pp5/rtg.jpg"));
        listChannels.add(new Movie("E TV","https://i.ibb.co/Jr6TRxn/e-tv.jpg"));
        listChannels.add(new Movie("Atameken Business","https://i.ibb.co/qyh4dRH/image.jpg"));
        listChannels.add(new Movie("Звезда","https://i.ibb.co/sjmDwvd/image.jpg"));
        listChannels.add(new Movie("Ювелирочка","https://i.ibb.co/r5nr4cT/image.jpg"));
        listChannels.add(new Movie("КТРК Спорт", "https://i.ibb.co/DLPyRYS/image.jpg"));

        listChannels.add(new Movie("Setanta Sport 1 HD", "https://i.ibb.co/vBsDzvv/111.jpg"));
        listChannels.add(new Movie("Setanta Sport 2 HD", "https://i.ibb.co/0yV27Rx/22.jpg"));
        listChannels.add(new Movie("Setanta Kyrgyzstan", "https://i.ibb.co/Lkbd5W3/Setanta-Kyrg.jpg"));
        listChannels.add(new Movie("Матч! Футбол 1","https://i.ibb.co/1vGtPyd/1.jpg"));
        listChannels.add(new Movie("Матч! Футбол 2","https://i.ibb.co/HDZ7v19/2.jpg"));
        listChannels.add(new Movie("Матч! Футбол 3","https://i.ibb.co/2Y6P4Dw/3.jpg"));
        listChannels.add(new Movie("Матч! Планета","https://i.ibb.co/37vzjNt/image.jpg"));
        listChannels.add(new Movie("Матч! Арена","https://i.ibb.co/wcpj7hD/image.jpg"));
        listChannels.add(new Movie("Матч! Премьер","https://i.ibb.co/sFDmTsV/image.jpg"));
        listChannels.add(new Movie("Матч! Страна","https://i.ibb.co/M7L3kpn/image.jpg"));
        listChannels.add(new Movie("Матч! ТВ", "https://i.ibb.co/5FQYB8L/image.jpg"));
        listChannels.add(new Movie("Матч! Боец", "https://i.ibb.co/qMv3M4q/1.jpg"));

        listChannels.add(new Movie("MMA-TV.com", "https://i.ibb.co/nPgrmvL/mmatv.jpg"));
        listChannels.add(new Movie("Бокс ТВ","https://i.ibb.co/GcXhdJf/1.jpg"));

        listChannels.add(new Movie("Кыргыз спорт", "https://i.ibb.co/KyTZWX0/image.jpg"));
        listChannels.add(new Movie("Q-Sport Arena", "https://i.ibb.co/Rp0XVgF/1.jpg"));

        listChannels.add(new Movie("Eurosport 1", "https://i.ibb.co/4gQ0hJz/1.jpg"));
        listChannels.add(new Movie("Eurosport 2", "https://i.ibb.co/2SvLhvs/2.jpg"));
        listChannels.add(new Movie("Viasat Sport", "https://i.ibb.co/rMqMZ4G/image.jpg"));

        listChannels.add(new Movie("KHL","https://i.ibb.co/ynXqdRj/2.jpg"));
        listChannels.add(new Movie("Точка отрыва","https://i.ibb.co/26X5tp1/image.jpg"));
        listChannels.add(new Movie("Русский экстрим","https://i.ibb.co/6Z3n6My/image.jpg"));
        listChannels.add(new Movie("Моторспорт ТВ","https://i.ibb.co/Tv0W6d0/motorsport.jpg"));
        listChannels.add(new Movie("Sport UZ","https://i.ibb.co/C1RYMxs/sport-uz.jpg"));
        listChannels.add(new Movie("Кино ТВ","https://i.ibb.co/PTDY7Lv/image.jpg"));
        listChannels.add(new Movie("CineMax","https://i.ibb.co/p1Vhjhq/CM.jpg"));
        listChannels.add(new Movie("Cinema","https://i.ibb.co/HKp9P6q/cinema.jpg"));
        listChannels.add(new Movie("NUR TV HD","https://i.ibb.co/MggTD61/nur-tv.jpg"));
        listChannels.add(new Movie("Дорама","https://i.ibb.co/StT52hr/image.jpg"));
        listChannels.add(new Movie("TV1.KG Бишкек-Шаары","https://i.ibb.co/5cxNzCd/TV1.jpg"));
        listChannels.add(new Movie("TV1.KG Бишкек City","https://i.ibb.co/303BfMC/TV1-City.jpg"));
        listChannels.add(new Movie("TV1.KG Cinemastan","https://i.ibb.co/DtJ4qvf/TV1-Cinemastan.jpg"));
        listChannels.add(new Movie("Кинопремьера","https://i.ibb.co/GHMpF6n/image.jpg"));
        listChannels.add(new Movie("Киносвидание","https://i.ibb.co/TTN2nyg/image.jpg"));
        listChannels.add(new Movie("Киносемья","https://i.ibb.co/4Ww2vpX/image.jpg"));
        listChannels.add(new Movie("Кинохит","https://i.ibb.co/w6TmF86/image.jpg"));
        listChannels.add(new Movie("Киномикс","https://i.ibb.co/7yGTqYq/image.jpg"));
        listChannels.add(new Movie("Родное кино","https://i.ibb.co/vYcggz2/image.jpg"));
        listChannels.add(new Movie("Наше новое кино","https://i.ibb.co/dDnwWxL/image.jpg"));
        listChannels.add(new Movie("Мужское кино","https://i.ibb.co/B4PZSNg/image.jpg"));
        listChannels.add(new Movie("Киноужас","https://i.ibb.co/jk5HpnQ/image.jpg"));
        listChannels.add(new Movie("Индийское кино","https://i.ibb.co/kBP86SG/image.jpg"));
        listChannels.add(new Movie("TV1000","https://i.ibb.co/N14JdDp/tv1000-2.jpg"));
        listChannels.add(new Movie("TV1000 Action","https://i.ibb.co/bNkNnYF/TV1000-Action.jpg"));
        listChannels.add(new Movie("TV1000 Русское кино","https://i.ibb.co/26HskgL/TV1000.jpg"));
        listChannels.add(new Movie("Амедия Хит HD","https://i.ibb.co/sP7BXk7/amedia-hit.jpg"));
        listChannels.add(new Movie("Amedia Premium HD","https://i.ibb.co/st7jpjp/A-media-premium.jpg"));
        listChannels.add(new Movie("A1 (Amedia)","https://i.ibb.co/fYC9hmd/a1.jpg"));
        listChannels.add(new Movie("A2 (Amedia)","https://i.ibb.co/8gR5XF9/a2.jpg"));
        listChannels.add(new Movie("Paramount Channel","https://i.ibb.co/1nqq94s/paramount.jpg"));
        listChannels.add(new Movie("Paramount Comedy","https://i.ibb.co/6tnr7pM/paramount-comedy.jpg"));
        listChannels.add(new Movie("Настоящее страшное ТВ","https://i.ibb.co/CMXJ7Qz/image.jpg"));
        listChannels.add(new Movie("Еврокино","https://i.ibb.co/PNbvzsT/image.jpg"));
        listChannels.add(new Movie("Fox Channel","https://i.ibb.co/CQqXxR3/fox-channel.jpg"));
        listChannels.add(new Movie("Fox Life","https://i.ibb.co/DVYNkkD/fox-life.jpg"));
        listChannels.add(new Movie("СТВ","https://i.ibb.co/Jx1SzfK/image.jpg"));
        listChannels.add(new Movie("Феникс+Кино","https://i.ibb.co/Db1fDZ0/image.jpg"));
        listChannels.add(new Movie("Sony Sci-Fi","https://i.ibb.co/vhgGrQr/sony-scifi.jpg"));
        listChannels.add(new Movie("Sony Turbo","https://i.ibb.co/gy6LqwK/Sony-Turbo.jpg"));
        listChannels.add(new Movie("Ретро ТВ","https://i.ibb.co/x71CryY/image.jpg"));
        listChannels.add(new Movie("Пятница 2.0","https://i.ibb.co/sP9z8M7/20.jpg"));
        listChannels.add(new Movie("Дом кино","https://i.ibb.co/pQNBJF3/image.jpg"));
        listChannels.add(new Movie("Дом кино Премиум HD","https://i.ibb.co/CPMvvkf/image.jpg"));
        listChannels.add(new Movie("Иллюзион+","https://i.ibb.co/0VNnLNh/image.jpg"));
        listChannels.add(new Movie("Русский Иллюзион","https://i.ibb.co/vX86hMR/image.jpg"));
        listChannels.add(new Movie("Мосфильм. Золотая коллекция","https://i.ibb.co/yqsrDY7/icon.jpg"));
        listChannels.add(new Movie("Бобёр","https://i.ibb.co/2M4T19S/image.jpg"));
        listChannels.add(new Movie("Ала-Тоо 24","https://i.ibb.co/bWRjxtK/24.jpg"));
        listChannels.add(new Movie("Россия 24", "https://i.ibb.co/P5Z3Mcd/24.jpg"));
        listChannels.add(new Movie("МИР 24","https://avatars.mds.yandex.net/get-vh/1535404/16416816241903537043-2e05zIO6YtezmFuc2qDnGA-1564411276/400x300"));
        listChannels.add(new Movie("Euronews Russia","https://i.ibb.co/vxrvVrb/image.jpg"));
        listChannels.add(new Movie("РБК","https://i.ibb.co/KGBF7z3/image.jpg"));
        listChannels.add(new Movie("Настоящее время", "https://i.ibb.co/M5DzVCG/image.jpg"));
        listChannels.add(new Movie("CGTN Русский", "https://i.ibb.co/W0cwjQH/cgtn.jpg"));
        listChannels.add(new Movie("КТРК Баластан","https://i.ibb.co/cYcVP0J/image.jpg"));
        listChannels.add(new Movie("Nickelodeon","https://i.ibb.co/gjJ60rD/image.jpg"));
        listChannels.add(new Movie("Nickelodeon HD","https://i.ibb.co/fYRzkC6/nick-hd.jpg"));
        listChannels.add(new Movie("Nick Junior","https://i.ibb.co/gJLvkdn/nick-jr.jpg"));
        listChannels.add(new Movie("Nick Toons","https://i.ibb.co/yfMz3mD/image.jpg"));
        listChannels.add(new Movie("В гостях у сказки","https://i.ibb.co/TqWvyYp/image.jpg"));
        listChannels.add(new Movie("Канал Disney","https://i.ibb.co/C2zxrr3/image.jpg"));
        listChannels.add(new Movie("TiJi","https://i.ibb.co/y5JTMVk/tiji.jpg"));
        listChannels.add(new Movie("Gulli Girl","https://i.ibb.co/Jjxp1xV/gulli-girl.jpg"));
        listChannels.add(new Movie("Мультландия","https://i.ibb.co/ZMtYYDn/image.jpg"));
        listChannels.add(new Movie("Мульт","https://i.ibb.co/m0HxsPb/image.jpg"));
        listChannels.add(new Movie("DaVinci Learning","https://i.ibb.co/vvqg8sw/image.jpg"));
        listChannels.add(new Movie("Мама","https://i.ibb.co/4SFCYfV/image.jpg"));
        listChannels.add(new Movie("Карусель","https://i.ibb.co/SJg9CJb/image.jpg"));
        listChannels.add(new Movie("TRT Çocuk ","https://i.ibb.co/rxP4731/trt-cocuk.jpg"));
        listChannels.add(new Movie("КТРК Музыка","https://i.ibb.co/0rwJPbN/image.jpg"));
        listChannels.add(new Movie("Tumar TV","https://i.ibb.co/xfc7k46/image.jpg"));
        listChannels.add(new Movie("ТНТ Music","https://i.ibb.co/gmcZYF7/music.jpg"));
        listChannels.add(new Movie("Bridge TV Русский Хит","https://i.ibb.co/jLLTQxW/image.jpg"));
        listChannels.add(new Movie("Bridge TV Classic","https://i.ibb.co/1JxT0JH/image.jpg"));
        listChannels.add(new Movie("Bridge TV Hits","https://i.ibb.co/k0k49CX/bridgetvhits.jpg"));
        listChannels.add(new Movie("Bridge TV","https://i.ibb.co/M7r1Fs7/bridgetv.jpg"));
        listChannels.add(new Movie("Bridge TV Шлягер","https://i.ibb.co/80kctft/image.jpg"));
        listChannels.add(new Movie("Ля-Минор","https://i.ibb.co/P5ckPw3/image.jpg"));
        listChannels.add(new Movie("MTV Россия","https://i.ibb.co/sHw9Bzy/image.jpg"));
        listChannels.add(new Movie("MTV Live HD","https://i.ibb.co/WHKTgmT/mtv-live-hd.jpg"));
        listChannels.add(new Movie("Европа Плюс ТВ","https://i.ibb.co/RQB2jB5/europa-plus.jpg"));
        listChannels.add(new Movie("Ru TV","https://i.ibb.co/F8bpSHy/image.jpg"));
        listChannels.add(new Movie("МузТВ","https://i.ibb.co/109SprY/image.jpg"));
        listChannels.add(new Movie("Россия Культура","https://i.ibb.co/GF2cCCq/image.jpg"));
        listChannels.add(new Movie("Вопросы Ответы","https://i.ibb.co/gdJC8DN/image.jpg"));
        listChannels.add(new Movie("Живая планета","https://i.ibb.co/0XZyf0R/image.jpg"));
        listChannels.add(new Movie("Канал История","https://i.ibb.co/w7g2Sgd/image.jpg"));
        listChannels.add(new Movie("HDL","https://i.ibb.co/pn017cr/hdl.jpg"));
        listChannels.add(new Movie("National Geographic","https://i.ibb.co/1qLjZ7j/national-geogr.jpg"));
        listChannels.add(new Movie("National Geographic Wild","https://i.ibb.co/Lv0rmDK/nat-geo-wild.jpg"));
        listChannels.add(new Movie("Discovery Channel","https://i.ibb.co/gFdM46Q/discovery-channel.jpg"));
        listChannels.add(new Movie("Viasat History","https://i.ibb.co/N9k6z0c/image.jpg"));
        listChannels.add(new Movie("Viasat Nature","https://i.ibb.co/H2p0nq6/image.jpg"));
        listChannels.add(new Movie("Viasat Explore","https://i.ibb.co/NLXBMCJ/image.jpg"));
        listChannels.add(new Movie("Охота и рыбалка","https://i.ibb.co/BgvL9cL/image.jpg"));
        listChannels.add(new Movie("Кухня ТВ","https://i.ibb.co/C8546xK/image.jpg"));
        listChannels.add(new Movie("Оружие","https://i.ibb.co/HzXBp3S/image.jpg"));
        listChannels.add(new Movie("Наука","https://i.ibb.co/Vt1QZ1d/2-0.jpg"));
        listChannels.add(new Movie("Драйв ТВ","https://i.ibb.co/8mXZY3Z/image.jpg"));
        listChannels.add(new Movie("Авто 24","https://i.ibb.co/kS9GJ0W/24.jpg"));
        listChannels.add(new Movie("Зоопарк","https://i.ibb.co/ZW8nq6G/image.jpg"));
        listChannels.add(new Movie("Домашние животные","https://i.ibb.co/Xsf7r35/image.jpg"));
        listChannels.add(new Movie("Авто плюс","https://i.ibb.co/Njs5Qzm/image.jpg"));
        listChannels.add(new Movie("Моя Планета","https://i.ibb.co/hmKRPCb/image.jpg"));
        listChannels.add(new Movie("Моя Планета HD","https://i.ibb.co/HxRnXwP/hd.jpg"));
        listChannels.add(new Movie("TRT World","https://i.ibb.co/jRc4wcj/trt-world.jpg"));
        listChannels.add(new Movie("TRT Haber","https://i.ibb.co/CP1nKFg/trt-haber.jpg"));
        listChannels.add(new Movie("TRT Muzik","https://i.ibb.co/HVfKmD6/trt-music.jpg"));
        listChannels.add(new Movie("TRT Spor","https://i.ibb.co/QCtNg2c/trt-spor.jpg"));
        listChannels.add(new Movie("Хабар","https://i.ibb.co/WDPX13L/kazakh-tv.jpg"));
        listChannels.add(new Movie("Qazaq TV","https://i.ibb.co/mBVmZGW/qazaq-tv.jpg"));
        listChannels.add(new Movie("Atameken Business","https://i.ibb.co/qyh4dRH/image.jpg"));
        listChannels.add(new Movie("Euronews English","https://i.ibb.co/PzbGyDC/image.jpg"));
        listChannels.add(new Movie("Russia Today","https://i.ibb.co/ggh7xtQ/russia-today.jpg"));
        listChannels.add(new Movie("Al Jazeera","https://i.ibb.co/drbY4b3/al-jazeera.jpg"));
        listChannels.add(new Movie("MyZen TV HD","https://i.ibb.co/Ksfv78f/image.jpg"));
        listChannels.add(new Movie("CNN","https://i.ibb.co/7tzPTDw/CNN-int.jpg"));
        listChannels.add(new Movie("Museum TV HD","https://i.ibb.co/wLFJsDj/museum.jpg"));
        listChannels.add(new Movie("CCTV 1","https://i.ibb.co/Fg7RcKt/cctv1.jpg"));
        listChannels.add(new Movie("CCTV 4","https://i.ibb.co/2NkVsbB/cctv4.jpg"));
        listChannels.add(new Movie("Uzbekistan TV","https://i.ibb.co/d2nfycy/ozbekiston1.jpg"));
        listChannels.add(new Movie("Ozbekiston24","https://i.ibb.co/zGPYgGv/ozbekiston-24.jpg"));
        listChannels.add(new Movie("MadaniyatVaMarifat ","https://i.ibb.co/W0VWXgw/madaniyat-va-marifat.jpg"));
        listChannels.add(new Movie("Navo","https://i.ibb.co/dMx9G07/Navo.jpg"));
        listChannels.add(new Movie("Dunyo Boylab","https://i.ibb.co/54B7L0p/dunya-boylab.jpg"));
        listChannels.add(new Movie("Mahalla","https://i.ibb.co/qx9V0Bb/mahalla.jpg"));
        listChannels.add(new Movie("Bolajon","https://i.ibb.co/hH0xBGQ/bolajon.jpg"));
        listChannels.add(new Movie("Kinoteatr UZ","https://i.ibb.co/VLKphGn/kinoteatr.jpg"));
        listChannels.add(new Movie("Yoshlar","https://i.ibb.co/zPkdGZ9/yoshlar.jpg"));
        listChannels.add(new Movie("France 24 Francais","https://i.ibb.co/CtrKZKb/france.jpg"));
        listChannels.add(new Movie("France 24 English","https://i.ibb.co/MB2gpZ4/france-eng.jpg"));
        listChannels.add(new Movie("CGTN ","https://i.ibb.co/5xbz3C1/cgtn.jpg"));
        return listChannels;
    }






}
